on:
 push:
  branches: [ master ]
 pull_request:
  branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
 # Checkout the code
    - uses: actions/checkout@v2
 # Setup version 9 of Java
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        path: target
 # Run all maven phases to deployment
 # with our repository as a target
    - name: Publish jar to GitHub Packages
      run: mvn deploy -X
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISTRIBUTION_ID: github
        DISTRIBUTION_NAME: Lingo Game
        DISTRIBUTION_URL: https://maven.pkg.github.com/${{ github.repository }}
